### ISSUE TITLE
Crash at startup when initing Bugsnag

### ISSUE THREAD

**Issue by daladim** [timusus/Shuttle2#128]
## 🌎 Environment

- Environment: S2 built from source
- Device: Nokia G21
- OS: Android 13
- App Version & Build: some commits on top of today's `main`
- Possible Cause: SD card removed?

## 💬 Description

S2 worked fine, until today, where my SD card got corrupt. Android is showing something that more or less says "there are issues with your SD card, click here to format it". The SD card is not visible to the apps (at least FX file explorer no longer shows it).
This SD card contained all my music and playlist files. And maybe some settings? There was an `Android` folder at its root.
That's the only reason I see to account for this new crash. (if that helps, a few other apps are behaving strangely)

Now, starting S2 immediately crashes with the following logs.
The important part seems to be `IllegalStateException: Bugsnag is unable to read config from manifest` (was it storing anything on my SD card?)

```
2023-05-22 21:57:58.702  7904-7904  AppInit                 com.simplecityapps.shuttle.dev       I  Initialising TimberInitializer
2023-05-22 21:57:58.703  7904-7904  AppInit                 com.simplecityapps.shuttle.dev       I  Initialising CrashReportingInitializer
2023-05-22 21:57:58.705  7904-7904  Bundle                  com.simplecityapps.shuttle.dev       W  Key com.bugsnag.android.API_KEY expected String but value was a java.lang.Integer.  The default value <null> was returned.
2023-05-22 21:57:58.706  7904-7904  Bundle                  com.simplecityapps.shuttle.dev       W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1377)
                                                                                                    	at com.bugsnag.android.ManifestConfigLoader.load$bugsnag_android_core_release(ManifestConfigLoader.kt:64)
                                                                                                    	at com.bugsnag.android.ManifestConfigLoader.load(ManifestConfigLoader.kt:50)
                                                                                                    	at com.bugsnag.android.ConfigInternal$Companion.load(ConfigInternal.kt:86)
                                                                                                    	at com.bugsnag.android.ConfigInternal$Companion.load(ConfigInternal.kt:82)
                                                                                                    	at com.bugsnag.android.ConfigInternal.load(Unknown Source:2)
                                                                                                    	at com.bugsnag.android.Configuration.load(Configuration.java:40)
                                                                                                    	at com.bugsnag.android.Bugsnag.start(Bugsnag.java:41)
                                                                                                    	at com.simplecityapps.shuttle.appinitializers.CrashReportingInitializer.init(CrashReportingInitializer.kt:25)
                                                                                                    	at com.simplecityapps.shuttle.appinitializers.AppInitializers.init(AppInitializers.kt:15)
                                                                                                    	at com.simplecityapps.shuttle.ShuttleApplication.onCreate(ShuttleApplication.kt:48)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6895)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8046)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
2023-05-22 21:57:58.707  7904-7904  AndroidRuntime          com.simplecityapps.shuttle.dev       D  Shutting down VM
2023-05-22 21:57:58.708  7904-7904  AndroidRuntime          com.simplecityapps.shuttle.dev       E  FATAL EXCEPTION: main
                                                                                                    Process: com.simplecityapps.shuttle.dev, PID: 7904
                                                                                                    java.lang.RuntimeException: Unable to create application com.simplecityapps.shuttle.ShuttleApplication: java.lang.IllegalStateException: Bugsnag is unable to read config from manifest.
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6901)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8046)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
                                                                                                    Caused by: java.lang.IllegalStateException: Bugsnag is unable to read config from manifest.
                                                                                                    	at com.bugsnag.android.ManifestConfigLoader.load(ManifestConfigLoader.kt:52)
                                                                                                    	at com.bugsnag.android.ConfigInternal$Companion.load(ConfigInternal.kt:86)
                                                                                                    	at com.bugsnag.android.ConfigInternal$Companion.load(ConfigInternal.kt:82)
                                                                                                    	at com.bugsnag.android.ConfigInternal.load(Unknown Source:2)
                                                                                                    	at com.bugsnag.android.Configuration.load(Configuration.java:40)
                                                                                                    	at com.bugsnag.android.Bugsnag.start(Bugsnag.java:41)
                                                                                                    	at com.simplecityapps.shuttle.appinitializers.CrashReportingInitializer.init(CrashReportingInitializer.kt:25)
                                                                                                    	at com.simplecityapps.shuttle.appinitializers.AppInitializers.init(AppInitializers.kt:15)
                                                                                                    	at com.simplecityapps.shuttle.ShuttleApplication.onCreate(ShuttleApplication.kt:48)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6895)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8046) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 
                                                                                                    Caused by: java.lang.IllegalArgumentException: No Bugsnag API key set
                                                                                                    	at com.bugsnag.android.ManifestConfigLoader.load$bugsnag_android_core_release(ManifestConfigLoader.kt:65)
                                                                                                    	at com.bugsnag.android.ManifestConfigLoader.load(ManifestConfigLoader.kt:50)
                                                                                                    	at com.bugsnag.android.ConfigInternal$Companion.load(ConfigInternal.kt:86) 
                                                                                                    	at com.bugsnag.android.ConfigInternal$Companion.load(ConfigInternal.kt:82) 
                                                                                                    	at com.bugsnag.android.ConfigInternal.load(Unknown Source:2) 
                                                                                                    	at com.bugsnag.android.Configuration.load(Configuration.java:40) 
                                                                                                    	at com.bugsnag.android.Bugsnag.start(Bugsnag.java:41) 
                                                                                                    	at com.simplecityapps.shuttle.appinitializers.CrashReportingInitializer.init(CrashReportingInitializer.kt:25) 
                                                                                                    	at com.simplecityapps.shuttle.appinitializers.AppInitializers.init(AppInitializers.kt:15) 
                                                                                                    	at com.simplecityapps.shuttle.ShuttleApplication.onCreate(ShuttleApplication.kt:48) 
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6895) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8046) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 
```

**Comment by timusus** [comment]
I'm not sure what happened here. But, I've removed Bugsnag in favour of Firebase Crashlytics
